version: '3'
services:
  sample-php-nodejs:
    build: .
    ports:
      - 3000:80
    volumes:
      - .:/var/www/html
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
