apiVersion: v1
kind: Service
metadata:
  name: sample-php-nodejs-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007  # NodePort to access app via Minikube IP
  selector:
    app: sample-php-nodejs-app
