apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"  # Set to true if using managed identity
    userAssignedIdentityID: "920698ad-a5b9-4698-91f3-ff0f63024ed7"  # Replace with the client ID of the managed identity
    keyvaultName: "KeyVaultSam2"  # Name of your Key Vault
    cloudName: ""                 # Leave empty for Azure Public Cloud
    tenantId: "84351664-87ef-40b4-b8c3-9674bd5623ea"  # Replace with your Azure tenant ID
    objects:  |
      array:
        - |
          objectName: mysql-host
          objectType: secret
        - |
          objectName: mysql-user
          objectType: secret
        - |
          objectName: mysql-password
          objectType: secret
